name: Coverage

on:  # Corre en cada PR
  pull_request:

jobs:
  coverage:
    name: Pytest coverage + Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test deps
        run: |
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=itec2025 --cov-report=xml  # genera coverage.xml en raíz

      - name: Upload to Codecov  # Requiere CODECOV_TOKEN si el repo es privado
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          fail_ci_if_error: true  # Falla si no puede subir (opcional)
