name: Docker image

on:
  push:
    tags: ['v*.*.*']  # Publica imagen al crear un tag semántico

jobs:
  docker:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Permite publicar en ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR  # Usa el token del repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .  # Carpeta del Dockerfile
          push: true  # Publica imagen
          tags: |
            ghcr.io/${{ github.repository }}:latest  # Etiqueta 'latest'
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}  # Etiqueta por tag
