name: pr-tests-and-email

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]

jobs:
  tests:
    name: Run pytest
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: itec2025.settings
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONPATH: ${{ github.workspace }}/itec2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest -q

  notify:
    name: Send email on success
    needs: tests
    if: success() && secrets.EMAIL_TO != ''
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail (Mailtrap SMTP)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_HOST }}
          server_port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_HOST_USER }}
          password: ${{ secrets.EMAIL_HOST_PASSWORD }}
          subject: "PR listo para mergear: #${{ github.event.pull_request.number }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM != '' && secrets.EMAIL_FROM || 'CI <ci@mailtrap.test>' }}
          secure: STARTTLS
          body: |
            El Pull Request #${{ github.event.pull_request.number }} pasó todos los pipelines.

            Repo: ${{ github.repository }}
            Título: ${{ github.event.pull_request.title }}
            Autor: ${{ github.event.pull_request.user.login }}
            URL: ${{ github.event.pull_request.html_url }}

            Estado: OK para mergear!
