name: Pre-commit  # Ejecuta los hooks de pre-commit en CI

on:  # Disparadores
  pull_request:  # Corre en cada PR

jobs:
  precommit:  # Job dedicado a pre-commit
    name: Run pre-commit hooks  # Título del job
    runs-on: ubuntu-latest  # Runner

    steps:
      - name: Checkout  # Descarga el repo
        uses: actions/checkout@v4

      - name: Setup Python  # Prepara Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Versión

      - name: Install pre-commit  # Instala la herramienta
        run: |
          pip install pre-commit

      - name: Run hooks  # Requiere .pre-commit-config.yaml en el repo
        run: |
          pre-commit run --all-files
