name: Security

on:  # Corre en cada PR
  pull_request:

jobs:
  deps_vulns:
    name: Dependencies & code security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tools
        run: |
          pip install -r requirements.txt
          pip install pip-audit bandit

      - name: Audit dependencies  # Vulnerabilidades en dependencias
        run: pip-audit

      - name: Bandit scan  # Análisis estático de seguridad
        run: bandit -q -r .
