name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Django pytest
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (pytest)
        env:
          # Si tu settings.py lee variables de entorno críticas, decláralas aquí o usa GitHub Secrets.
          # DJANGO_SETTINGS_MODULE está definido en itec2025/pytest.ini
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
        run: |
          pytest -q
