name: Run Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Django Tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: ${{ github.workspace }}
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (Pytest)
      run: pytest -q