name: Types  # Chequeo de tipos con mypy

on:  # Disparadores del workflow
  pull_request:  # Se ejecuta en cada PR

jobs:
  mypy:  # Job de análisis estático de tipos
    name: mypy (type checking)  # Título del job
    runs-on: ubuntu-latest  # Runner de GitHub

    steps:
      - name: Checkout  # Trae el código al runner
        uses: actions/checkout@v4

      - name: Setup Python  # Prepara Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Versión objetivo

      - name: Install mypy and stubs  # mypy + stubs de Django
        run: |
          pip install -r requirements.txt
          pip install mypy django-stubs

      - name: Run mypy  # Analiza tipos
        run: |
          mypy .
        env:
          # Si tu proyecto requiere configuraciones especiales de mypy,
          # agregá un mypy.ini o pyproject.toml con sección [tool.mypy].
          PYTHONUNBUFFERED: 1
